# Generated by Django 5.2.15 on 2026-07-26 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='weight',
            field=models.DecimalField(decimal_places=2, default=0.6, help_text='Weight in KG per unit', max_digits=6),
        ),
    ]
