# Generated by Django 5.2.15 on 2026-07-26 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_orderstatushistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('cod', 'Cash On Delivery'), ('upi', 'UPI'), ('card', 'Card'), ('netbanking', 'Net Banking'), ('razorpay', 'Razorpay / Online Payment')], max_length=20),
        ),
    ]
