# Generated by Django 5.2.16 on 2026-07-19 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StoreSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_name', models.CharField(default='3Seven Studio', max_length=150)),
                ('currency', models.CharField(default='INR', max_length=10)),
                ('support_email', models.EmailField(blank=True, max_length=254)),
                ('support_phone', models.CharField(blank=True, max_length=20)),
                ('maintenance_mode', models.BooleanField(default=False)),
                ('gst_enabled', models.BooleanField(default=False)),
                ('gst_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('free_shipping', models.BooleanField(default=True)),
                ('shipping_charge', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('cod_enabled', models.BooleanField(default=True)),
                ('cod_charge', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('coupon_enabled', models.BooleanField(default=False)),
                ('payment_gateway_enabled', models.BooleanField(default=False)),
                ('payment_gateway', models.CharField(choices=[('none', 'None'), ('razorpay', 'Razorpay'), ('cashfree', 'Cashfree'), ('phonepe', 'PhonePe'), ('payu', 'PayU'), ('stripe', 'Stripe')], default='none', max_length=30)),
                ('upi_enabled', models.BooleanField(default=True)),
                ('card_enabled', models.BooleanField(default=False)),
                ('wallet_enabled', models.BooleanField(default=False)),
                ('netbanking_enabled', models.BooleanField(default=False)),
                ('payment_gateway_key', models.CharField(blank=True, max_length=255)),
                ('payment_gateway_secret', models.CharField(blank=True, max_length=255)),
                ('webhook_secret', models.CharField(blank=True, max_length=255)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Store Settings',
                'verbose_name_plural': 'Store Settings',
            },
        ),
    ]
