# Generated by Django 5.2.16 on 2026-07-25 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='scope',
            field=models.CharField(choices=[('all', 'Entire Store'), ('category', 'Selected Categories'), ('product', 'Selected Products')], default='all', max_length=20),
        ),
    ]
