# Generated by Django 5.2.16 on 2026-07-25 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0002_coupon_scope'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coupon',
            options={'ordering': ['priority', '-created_at']},
        ),
        migrations.AddField(
            model_name='coupon',
            name='auto_apply',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='coupon',
            name='customer_selection',
            field=models.CharField(choices=[('all', 'All Customers'), ('new', 'New Customers'), ('existing', 'Existing Customers')], default='all', max_length=20),
        ),
        migrations.AddField(
            model_name='coupon',
            name='priority',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
